### ISSUE TITLE
broadcast on the transaction dialog window.

### ISSUE THREAD

**Issue by brakab** [cashshuffle/cashshuffle-electron-cash-plugin#18]
How do I broadcast? I suspect there is one other person trying to cash shuffle so I need to broadcast to more people. I don't see the broadcast option on the transaction dialog window.

**Comment by brakab** [comment]
It says:
Console output go here
Player 2 get session number.

**Comment by clifordsymack** [comment]
Hi @brakab !
Every server should be configured to accept number of players. You got the message that you are the second player in the pool. Sever is waiting for the next players to proceed. For example if server is configured for pool with 3 players it will wait for the third player. After pool will be completed the main shuffling started. After complete of shuffling dialog window for broafcasting the transaction appears
