### ISSUE TITLE
add my Tor hidden server to the default list

### ISSUE THREAD

**Issue by HiddenCashShuffle** [cashshuffle/cashshuffle-electron-cash-plugin#2]
Very exciting project. I just setup a server behind Tor to help make this project even more private. 

cbofdrwfez4b7j7d.onion:80. There is no SSL since it is using Tor

**Comment by zquestz** [comment]
Would give you extra credit if you setup SSL. =)

**Comment by HiddenCashShuffle** [comment]
I can setup SSL, but the certificate will be self signed. Is that okay? If so, I will do it. It will only take a few minutes.

**Comment by clifordsymack** [comment]
I added your server to the list
