### ISSUE TITLE
Add an ability to cancel a shuffle

### ISSUE THREAD

**Issue by ifol** [cashshuffle/cashshuffle-electron-cash-plugin#20]
I started a shuffle about an hour ago on cashmixer.org server and nothing happened since then. I assume there are not enough players to commence the shuffling process?

I'd like to cancel the round and join another server, maybe I'll have better luck there for more players, however CashShuffle plugin doesn't let me cancel, it's all just grayed out. Should I just quit Electrum and try again?

It would be good if there was a cancel button.

**Comment by clifordsymack** [comment]
@ifol Yes will add it soon

**Comment by zquestz** [comment]
This has been added. Thanks for the suggestion. =)
