### ISSUE TITLE
Coins can be stolen, because peer continues after failed address verification

### ISSUE THREAD

**Issue by real-or-random** [cashshuffle/cashshuffle-electron-cash-plugin#24]
If a peer notices that the own output address is not in `__new_addresses`, it raises `BlameException` in
https://github.com/cashshuffle/cashshuffle-electron-cash-plugin/blob/bcd9d668dcde92649be78e445da5820ee79b7ffa/shuffle/coin_shuffle.py#L295. Since this exception is caught in the next line,  peer continues, eventually signing the transaction with the wrong `__new_addresses`, leading to potential theft of coins.

**Comment by clifordsymack** [comment]
@real-or-random Thanks a lot for this review. I should add more test on it for sure

**Comment by zquestz** [comment]
Thank you for the review. Appreciate more people looking over this. That is why it is still a dev build.

**Comment by clifordsymack** [comment]
This case processed now.
