### ISSUE TITLE
Unlinkability broken due to missing equality check

### ISSUE THREAD

**Issue by real-or-random** [cashshuffle/cashshuffle-electron-cash-plugin#25]
Peers need to check if there are duplicate ciphertexts after decryption. If not, attacks on unlinkability are possible. This check is missing here after this line:
https://github.com/cashshuffle/cashshuffle-electron-cash-plugin/blob/bcd9d668dcde92649be78e445da5820ee79b7ffa/shuffle/coin_shuffle.py#L243

As co-author of the CoinShuffle paper, I recommend everybody not to use this plugin. It has not been audited properly and potentially contains more serious flaws. Moreover, the CoinShuffle protocol is outdated, [CoinShuffle++](https://crypsys.mmci.uni-saarland.de/projects/FastDC/paper.pdf) is better in every aspect. No coin mixing protocol should be used without [very careful coin control mechanisms](https://medium.com/@nopara73/coin-control-is-must-learn-if-you-care-about-your-privacy-in-bitcoin-33b9a5f224a2) built in the client, because it's a huge cannon for anonymity.

**Comment by zquestz** [comment]
What would be the steps to have this formally reviewed? Would love to get this audited by more folks. I only wrote the server side, and have limited context on the plugin itself.

**Comment by zquestz** [comment]
So just to be clear, a plugin that is in development and not released is something you are actively going to tell people not to use? Well we didn't intend for it to be used either, that would be why we put out a dev release, to get reviews started, and fix bugs in the underlying implementation.

At no time have we said this is production ready. Just to be very clear.

**Comment by real-or-random** [comment]
I don't know your intentions and I see your point that there is no official release so far.
The thing is: Neither the website nor the README mention that it is a development version. Instead, the README contains detailed installation instructions that not only advanced developers can use. And even advanced developers probably don't want to lose their coins. If your intention is that people should not use this currently, then this should be made very clear. Even better, it should be configured to only work on testnet.

If you need an audit: There are people who do security audits for money. Personally I'm not interested in doing an audit, because I think this old version of CoinShuffle is obsolete. There is CoinShuffle++, which is much faster and simpler. That also means it easier  simpler to implement. There is no reason to the old CoinShuffle.

**Comment by zquestz** [comment]
There is already effort underway to do CoinShuffle++. We did this first to become more familiar with the protocol. That was already our plan.

Since you worked on the original CoinShuffle, do you have suggestions on people who we should reach out to for an audit?

**Comment by real-or-random** [comment]
Okay, then you should know that CoinShuffle++ is pretty different from the old CoinShuffle. The biggest similarity is that it follows the same paradigm of "try to shuffle. if it fails, break anonymity and exclude the evil guy".

**Comment by clifordsymack** [comment]
duplicate ciphertexts are checked now
