### ISSUE TITLE
Protocol does not terminate in the presence of malicious peers

### ISSUE THREAD

**Issue by real-or-random** [cashshuffle/cashshuffle-electron-cash-plugin#26]
There are a lot of issues, e.g., peers can apparently can equivocate with their change address, or parse errors are not handled here:
https://github.com/cashshuffle/cashshuffle-electron-cash-plugin/blob/bcd9d668dcde92649be78e445da5820ee79b7ffa/shuffle/coin_shuffle.py#L141

**Comment by clifordsymack** [comment]
This is not actual on current version of code. All messages coming into incoming channel parsed with exception catching here
https://github.com/cashshuffle/cashshuffle-electron-cash-plugin/blob/master/shuffle/coin_shuffle.py#L125

If parsing goes wel message go to inbox and other logic processed from it.
