### ISSUE TITLE
 BlameException: Wrong tx signature from player 1

### ISSUE THREAD

**Issue by marceloneil** [cashshuffle/cashshuffle-electron-cash-plugin#29]
Exception recorded by the Electron Cash crash reporting system: https://github.com/fyookball/electrum/issues/657

>Crash Report
>============
>
>This crash report was reported through the automatic crash reporting system 🤖
>
>Traceback
>--------------
>
>```Python traceback
>  File "/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.1.6-py3.5.egg/electroncash/util.py", line 613, in run_with_except_hook
>    run_original(*args2, **kwargs2)
>  File "/usr/lib/python3.5/threading.py", line 862, in run
>    self._target(*self._args, **self._kwargs)
>  File "/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.1.6-py3.5.egg/electroncash_plugins/shuffle/coin_shuffle.py", line 540, in protocol_loop
>    self.process_inbox()
>  File "/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.1.6-py3.5.egg/electroncash_plugins/shuffle/coin_shuffle.py", line 515, in process_inbox
>    self.process_verification_and_submission()
>  File "/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.1.6-py3.5.egg/electroncash_plugins/shuffle/coin_shuffle.py", line 372, in process_verification_and_submission
>    raise BlameException('Wrong tx signature from player ' + str(player))
>
>BlameException: Wrong tx signature from player 1
>```
>
>Reporter
>------------
>
>This issue was reported by 2 user(s):
>
>| Electrum Version  | Operating System  | Wallet Type  | Locale |
>|---|---|---|---|
>| 3.1.6  | Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial | standard | de_CH |
>| 3.1.6  | Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial | standard | de_CH |
>
>
>Additional Information
>------------------------
>
>
>> try to shuffle with own shuffleserver (-s 2)  ...two clients shuffle failed
>
>---
>

**Comment by clifordsymack** [comment]
@marceloneil can you tell more about how you get it? Plugin stop execution because it got wrong transaction signature from player 1

**Comment by marceloneil** [comment]
Sorry, someone else reported this crash using our system (I don't know who). Just the information provided (traceback, OS, information, etc.)

**Comment by clifordsymack** [comment]
Good idea. WIll close it.
