### ISSUE TITLE
Error: cannot register on the pool

### ISSUE THREAD

**Issue by KainniaK** [cashshuffle/cashshuffle-electron-cash-plugin#30]
Trying to shuffle with electroncash.checksum0.com

**Comment by clifordsymack** [comment]
@KainniaK thanks for respond. Will review soon. Did you tried to connect to other servers from list?

**Comment by clifordsymack** [comment]
@KainniaK  it looks working now. Maybe it was shutdowned before. Here is a transaction made with this  server on the testnet 
https://www.blocktrail.com/tBCC/tx/8143b02d9af3c9f64c7ac437da40a457e7a81c4cc4b4194ff020721a17af646e

**Comment by KainniaK** [comment]
There are only three servers in my list. One is a onion one and I don't have TOR installed. The other one does not reply to my pings and when I try connect to it, it crahes electron cash.

The electroncash.checksum0.com is responding on testnet but not on mainnet. 

Watch [my  video](https://www.youtube.com/watch?v=J0YyE7zEtBo) for my issues so far. I am a user helping the community by testing this stuff from a user perspective so that there will be more data generated that can help devs and also to keep the community up to data on progress made.

**Comment by clifordsymack** [comment]
@KainniaK i've tested checksum0's server on mainnet and it looks working. I can't test 3 open electron-cash instanses because i can't start more then one instances on my pc. What linux distribution you are using?

**Comment by KainniaK** [comment]
I am using Linux Mint 18 point something

**Comment by clifordsymack** [comment]
Problem from video should disappear now.
