### ISSUE TITLE
Install difficulties on Ubuntu 16.04

### ISSUE THREAD

**Issue by cryptophone** [cashshuffle/cashshuffle-electron-cash-plugin#31]
To get set up with CashShuffle, I used a fresh install of Ubuntu 16.04.  However I hit several snags while following the setup guide at https://github.com/cashshuffle/cashshuffle-electron-cash-plugin/blob/master/README.md.  I also needed to:

1.  Install "setuptools".
2.  Install "python3-pyqt5"
3.  Install version 3.2 (rather than 3.0) of Electron Cash
4.  Remove "pyqt5" from the requirements list in setup.py

The following command works on my system to achieve these things.  I also added "set -x" to help with 
debugging.

`set -x; if [ ! $(which setuptools) ]; then sudo apt-get install python3-setuptools; fi; if ! dpkg -l python3-pyqt5 >/dev/null; then sudo apt-get install python3-pyqt5; fi; cd ~/ && V="3.2" && EC_GZ="ElectronCash-$V.tar.gz" && EC_DIR="Electron Cash-$V" && wget "https://electroncash.org/downloads/$V/win-linux/$EC_GZ" && tar -xvzf "$EC_GZ" && rm -rf "$EC_GZ" && wget https://github.com/cashshuffle/cashshuffle-electron-cash-plugin/archive/master.zip && unzip master.zip && rm -rf master.zip && rm -rf "$EC_DIR/plugins/shuffle" && mv cashshuffle-electron-cash-plugin-master/shuffle "$EC_DIR/plugins" && rm -rf cashshuffle-electron-cash-plugin-master && sed -i "s/'electroncash_plugins.virtualkeyboard',/'electroncash_plugins.virtualkeyboard', 'electroncash_plugins.shuffle',/" "$EC_DIR/setup.py" && sed -i '/'\''pyqt5'\'',/d' "$EC_DIR/setup.py" && cd "$EC_DIR" && sudo python3 setup.py install; set +x`

**Comment by clifordsymack** [comment]
I've tested it with 3.1.6 version of electron-cash. Will test it on 3.2 maybe there is some issues.

**Comment by clifordsymack** [comment]
@cryptophone do you install electron-cash from source or get it as a package?

**Comment by cryptophone** [comment]
@clifordsymack I just followed the guide at https://github.com/cashshuffle/cashshuffle-electron-cash-plugin/blob/master/README.md.  All I did prior to this was install a fresh copy of Ubuntu 16.04.

This includes the step: `wget https://electroncash.org/downloads/3.0/win-linux/ElectronCash-3.0.tar.gz`.  So, if people follow the README as it currently stands, they will end up getting version 3.0 from that package, which won't work, as far as I can see.

**Comment by cryptophone** [comment]
I see now the statement at the top of the file that says 

> The version of Electron Cash should be not less then 3.1.2

However the command below this is said to "install the latest version of Electron Cash", but it doesn't.  It installs version 3.0.  I'm sure this will trip up people.

I had a look to see if I could modify the instruction to properly get the latest version, but this would involve installing git, etc.  And I don't know how involved you want this instruction to be.  So the version of the command I gave earlier at least makes the version number a variable so it's easier to update.

**Comment by clifordsymack** [comment]
I will try the installation in a fresh ubuntu VM.  And instruction should be changed for sure.

**Comment by zquestz** [comment]
Going to close this. We now have a new install method that replaces the old docs. This is no longer relevant.
