### ISSUE TITLE
Provide a EC 3.3+ plugin release

### ISSUE THREAD

**Issue by rt121212121** [cashshuffle/cashshuffle-electron-cash-plugin#32]
I am looking to disable manual plugin installation for future versions of Electron Cash because there is no code or UI support for differentiating between plugins installled by the UI plugin manager and  manually.  Is there any reason why cashshuffle repo can't be updated with a new style zip-based plugin?  There's a zip creation tool you can just point at your repo, fill in a few extra fields and upload the release to your repo.

**Comment by fyookball** [comment]
I was under the impression the new 3_0 release of cash shuffle is that format

**Comment by rt121212121** [comment]
Ah, sorry, the github readme/home page still talks about manual installation.  I guess I should make a pull request to update it.
