### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rt121212121** [cashshuffle/cashshuffle-electron-cash-plugin#33]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "C:\Users\cmurray\AppData\Local\ElectronCash\external_plugins\shuffle_040.zip\shuffle\qt.py", line 114, in update_inputs
    self.coinshuffle_inputs.update(self.window.wallet)
  File "C:\Users\cmurray\AppData\Local\ElectronCash\external_plugins\shuffle_040.zip\shuffle\shuffle.py", line 81, in update
    current_input = self.get_input_address()
  File "C:\Users\cmurray\AppData\Local\ElectronCash\external_plugins\shuffle_040.zip\shuffle\shuffle.py", line 101, in get_input_address
    return self.inputsArray[self.currentIndex()]['address']

IndexError: list index out of range
```

Reporter
------------

This issue was reported by 2 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.3  | Windows-10-10.0.17134 | standard | en_US |
| 3.3  | Windows-7-6.1.7601-SP1 | standard | en_US |

Additional Information
------------------------

> Installed cashshuffle plugin and getting random bugs now

---

user says "it was just repeatedly popping up with the plugin installed, not even trying to shuffle"
--

**Comment by rt121212121** [comment]
This is copied from here:
https://github.com/fyookball/electrum/issues/787

**Comment by clifordsymack** [comment]
@rt121212121 I just updated the binary in release. Can you check it? It should work now

**Comment by rt121212121** [comment]
I've never used it.  Just moving the automatically reported issues that come via Electron Cash over here, so we can close them locally :-)

**Comment by clifordsymack** [comment]
Fixed already.
