### ISSUE TITLE
Instructions in README.md are dangerous

### ISSUE THREAD

**Issue by EchterAgo** [cashshuffle/cashshuffle-electron-cash-plugin#36]
The installation instructions result in an Electron Cash version 3.0 installation. Version 3.0 was released December of last year and is still affected by the JSONRPC security vulnerability. The instructions should be updated, I'd recommend removing information on how to install Electron Cash and only keeping information on how to install the plugin into an existing Electron Cash installation.

**Comment by EchterAgo** [comment]
Generally the plugin installation process seems to be a lot smoother nowadays. I just posted on Electron-Cash/Electron-Cash/issues/869 about how to install the plugin and those instructions likely work for all platforms. Consider the text public domain, feel free to copy it.

**Comment by clifordsymack** [comment]
Hi @EchterAgo !

Thanks for this comment. I will update the installation part on README.

**Comment by EchterAgo** [comment]
@chaintip 100 days

**Comment by chaintip** [comment]
`0.00909355 BCH`| `~   4.99 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4dlpq6xeepmw8ve8l9usn80q68jys3vgd7xz) to this issue by @EchterAgo.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/47), get a pull request merged with ```@chaintip fixes #36``` in the creation comment.

**Comment by clifordsymack** [comment]
Updated.

**Comment by EchterAgo** [comment]
If you reopen this and close it with a pull request you can claim the tip I sent.

**Comment by chaintip** [comment]
`0.00909355 BCH`| `~   4.96 USD` has now been claimed by @clifordsymack when pull request [#37](http://github.chaintip.org/cashshuffle/cashshuffle-electron-cash-plugin/pull/37) was merged. This will be sent to your wallet once you link it with chaintip.
