### ISSUE TITLE
Prevent address reuse of the plugin

### ISSUE THREAD

**Issue by checksum0** [cashshuffle/cashshuffle-electron-cash-plugin#8]
The plugin currently offer the possibility to reuse address both in the output and change field. Address reuse should be impossible once an address as been used as it significantly decrease the privacy of the shuffler doing so as well as all the other shufflers involved in the round.

**Comment by clifordsymack** [comment]
I add the checkbox for selecting the only fresh change addresses. Due to electron-cash entire logic it looks at the history of the wallet and delete used addresses from the list.
